# Generated by Django 4.0 on 2021-12-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('url_demo', models.URLField(blank=True, null=True, verbose_name='Link de la demostracion del Sitio')),
                ('url_github_user', models.URLField(blank=True, null=True, verbose_name='Link de la cuenta del usuario en Github')),
            ],
        ),
    ]
